# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_noduleme.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(1251, 690)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../nodule_me.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWidget.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 3, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonOpen = QtWidgets.QPushButton(MainWidget)
        self.buttonOpen.setObjectName("buttonOpen")
        self.horizontalLayout_2.addWidget(self.buttonOpen)
        self.buttonSave = QtWidgets.QPushButton(MainWidget)
        self.buttonSave.setObjectName("buttonSave")
        self.horizontalLayout_2.addWidget(self.buttonSave)
        self.buttonSaveAsNew = QtWidgets.QPushButton(MainWidget)
        self.buttonSaveAsNew.setObjectName("buttonSaveAsNew")
        self.horizontalLayout_2.addWidget(self.buttonSaveAsNew)
        spacerItem = QtWidgets.QSpacerItem(10000, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.comboBoxUser = QtWidgets.QComboBox(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxUser.sizePolicy().hasHeightForWidth())
        self.comboBoxUser.setSizePolicy(sizePolicy)
        self.comboBoxUser.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxUser.setObjectName("comboBoxUser")
        self.comboBoxUser.addItem("")
        self.comboBoxUser.addItem("")
        self.comboBoxUser.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxUser)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(MainWidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 4, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, -1, 0, -1)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonPen = QtWidgets.QToolButton(MainWidget)
        self.buttonPen.setMinimumSize(QtCore.QSize(30, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/pen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPen.setIcon(icon1)
        self.buttonPen.setObjectName("buttonPen")
        self.gridLayout.addWidget(self.buttonPen, 0, 0, 1, 1)
        self.buttonTube = QtWidgets.QPushButton(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonTube.sizePolicy().hasHeightForWidth())
        self.buttonTube.setSizePolicy(sizePolicy)
        self.buttonTube.setMinimumSize(QtCore.QSize(30, 30))
        self.buttonTube.setMaximumSize(QtCore.QSize(30, 30))
        self.buttonTube.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui/tube.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonTube.setIcon(icon2)
        self.buttonTube.setObjectName("buttonTube")
        self.gridLayout.addWidget(self.buttonTube, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.buttonPinset = QtWidgets.QToolButton(MainWidget)
        self.buttonPinset.setMinimumSize(QtCore.QSize(30, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui/pinset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPinset.setIcon(icon3)
        self.buttonPinset.setObjectName("buttonPinset")
        self.gridLayout.addWidget(self.buttonPinset, 1, 0, 1, 1)
        self.buttonEracer = QtWidgets.QPushButton(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEracer.sizePolicy().hasHeightForWidth())
        self.buttonEracer.setSizePolicy(sizePolicy)
        self.buttonEracer.setMinimumSize(QtCore.QSize(30, 30))
        self.buttonEracer.setMaximumSize(QtCore.QSize(30, 30))
        self.buttonEracer.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonEracer.setIcon(icon4)
        self.buttonEracer.setObjectName("buttonEracer")
        self.gridLayout.addWidget(self.buttonEracer, 2, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(MainWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 4, 0, 1, 1)
        self.buttonACMSnake = QtWidgets.QPushButton(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonACMSnake.sizePolicy().hasHeightForWidth())
        self.buttonACMSnake.setSizePolicy(sizePolicy)
        self.buttonACMSnake.setMinimumSize(QtCore.QSize(30, 30))
        self.buttonACMSnake.setMaximumSize(QtCore.QSize(30, 30))
        self.buttonACMSnake.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ui/acm_snake.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonACMSnake.setIcon(icon5)
        self.buttonACMSnake.setObjectName("buttonACMSnake")
        self.gridLayout.addWidget(self.buttonACMSnake, 5, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(MainWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelImage = CanvasView(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImage.sizePolicy().hasHeightForWidth())
        self.labelImage.setSizePolicy(sizePolicy)
        self.labelImage.setMinimumSize(QtCore.QSize(500, 500))
        self.labelImage.setMaximumSize(QtCore.QSize(2000, 2000))
        self.labelImage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelImage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelImage.setObjectName("labelImage")
        self.horizontalLayout_10.addWidget(self.labelImage)
        self.scrollBarY = QtWidgets.QScrollBar(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollBarY.sizePolicy().hasHeightForWidth())
        self.scrollBarY.setSizePolicy(sizePolicy)
        self.scrollBarY.setOrientation(QtCore.Qt.Vertical)
        self.scrollBarY.setObjectName("scrollBarY")
        self.horizontalLayout_10.addWidget(self.scrollBarY)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.scrollBarX = QtWidgets.QScrollBar(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollBarX.sizePolicy().hasHeightForWidth())
        self.scrollBarX.setSizePolicy(sizePolicy)
        self.scrollBarX.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBarX.setObjectName("scrollBarX")
        self.verticalLayout_3.addWidget(self.scrollBarX)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sliderIndex = QtWidgets.QSlider(MainWidget)
        self.sliderIndex.setOrientation(QtCore.Qt.Horizontal)
        self.sliderIndex.setObjectName("sliderIndex")
        self.horizontalLayout_4.addWidget(self.sliderIndex)
        self.spinIndex = QtWidgets.QSpinBox(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinIndex.sizePolicy().hasHeightForWidth())
        self.spinIndex.setSizePolicy(sizePolicy)
        self.spinIndex.setMinimumSize(QtCore.QSize(61, 0))
        self.spinIndex.setObjectName("spinIndex")
        self.horizontalLayout_4.addWidget(self.spinIndex)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.widgetWritting = QtWidgets.QWidget(MainWidget)
        self.widgetWritting.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetWritting.sizePolicy().hasHeightForWidth())
        self.widgetWritting.setSizePolicy(sizePolicy)
        self.widgetWritting.setMinimumSize(QtCore.QSize(200, 0))
        self.widgetWritting.setMaximumSize(QtCore.QSize(0, 16777215))
        self.widgetWritting.setObjectName("widgetWritting")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widgetWritting)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labelLayout = QtWidgets.QVBoxLayout()
        self.labelLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.labelLayout.setContentsMargins(0, -1, -1, -1)
        self.labelLayout.setSpacing(4)
        self.labelLayout.setObjectName("labelLayout")
        self.label = QtWidgets.QLabel(self.widgetWritting)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.labelLayout.addWidget(self.label)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.widgetWritting)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.radioButton5 = QtWidgets.QRadioButton(self.widgetWritting)
        self.radioButton5.setObjectName("radioButton5")
        self.verticalLayout_10.addWidget(self.radioButton5)
        self.radioButton4 = QtWidgets.QRadioButton(self.widgetWritting)
        self.radioButton4.setObjectName("radioButton4")
        self.verticalLayout_10.addWidget(self.radioButton4)
        self.radioButton3 = QtWidgets.QRadioButton(self.widgetWritting)
        self.radioButton3.setObjectName("radioButton3")
        self.verticalLayout_10.addWidget(self.radioButton3)
        self.radioButton2 = QtWidgets.QRadioButton(self.widgetWritting)
        self.radioButton2.setObjectName("radioButton2")
        self.verticalLayout_10.addWidget(self.radioButton2)
        self.radioButton1 = QtWidgets.QRadioButton(self.widgetWritting)
        self.radioButton1.setObjectName("radioButton1")
        self.verticalLayout_10.addWidget(self.radioButton1)
        self.labelLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.widgetWritting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.textEditCommentsWritting = QtWidgets.QPlainTextEdit(self.widgetWritting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditCommentsWritting.sizePolicy().hasHeightForWidth())
        self.textEditCommentsWritting.setSizePolicy(sizePolicy)
        self.textEditCommentsWritting.setMaximumSize(QtCore.QSize(200, 100))
        self.textEditCommentsWritting.setObjectName("textEditCommentsWritting")
        self.verticalLayout_11.addWidget(self.textEditCommentsWritting)
        self.labelLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.widgetWritting)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.comboBoxNoduleIdWritting = QtWidgets.QComboBox(self.widgetWritting)
        self.comboBoxNoduleIdWritting.setObjectName("comboBoxNoduleIdWritting")
        self.verticalLayout_12.addWidget(self.comboBoxNoduleIdWritting)
        self.labelLayout.addLayout(self.verticalLayout_12)
        self.line_6 = QtWidgets.QFrame(self.widgetWritting)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.labelLayout.addWidget(self.line_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.buttonDeleteWritting = QtWidgets.QPushButton(self.widgetWritting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDeleteWritting.sizePolicy().hasHeightForWidth())
        self.buttonDeleteWritting.setSizePolicy(sizePolicy)
        self.buttonDeleteWritting.setMinimumSize(QtCore.QSize(30, 30))
        self.buttonDeleteWritting.setMaximumSize(QtCore.QSize(30, 30))
        self.buttonDeleteWritting.setStyleSheet("background-color: rgb(255, 85, 127);")
        self.buttonDeleteWritting.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ui/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDeleteWritting.setIcon(icon6)
        self.buttonDeleteWritting.setObjectName("buttonDeleteWritting")
        self.horizontalLayout.addWidget(self.buttonDeleteWritting)
        self.labelLayout.addLayout(self.horizontalLayout)
        self.tableWidgetWritting = QtWidgets.QTableWidget(self.widgetWritting)
        self.tableWidgetWritting.setObjectName("tableWidgetWritting")
        self.tableWidgetWritting.setColumnCount(1)
        self.tableWidgetWritting.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetWritting.setHorizontalHeaderItem(0, item)
        self.labelLayout.addWidget(self.tableWidgetWritting)
        self.buttonOkWritting = QtWidgets.QPushButton(self.widgetWritting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOkWritting.sizePolicy().hasHeightForWidth())
        self.buttonOkWritting.setSizePolicy(sizePolicy)
        self.buttonOkWritting.setMinimumSize(QtCore.QSize(70, 32))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonOkWritting.setFont(font)
        self.buttonOkWritting.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.buttonOkWritting.setObjectName("buttonOkWritting")
        self.labelLayout.addWidget(self.buttonOkWritting)
        self.verticalLayout_7.addLayout(self.labelLayout)
        self.horizontalLayout_3.addWidget(self.widgetWritting)
        self.line_3 = QtWidgets.QFrame(MainWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonZoomUp = QtWidgets.QToolButton(MainWidget)
        self.buttonZoomUp.setMinimumSize(QtCore.QSize(30, 30))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ui/zoom_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonZoomUp.setIcon(icon7)
        self.buttonZoomUp.setObjectName("buttonZoomUp")
        self.horizontalLayout_5.addWidget(self.buttonZoomUp)
        self.buttonZoomDown = QtWidgets.QToolButton(MainWidget)
        self.buttonZoomDown.setMinimumSize(QtCore.QSize(30, 30))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("ui/zoom_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonZoomDown.setIcon(icon8)
        self.buttonZoomDown.setObjectName("buttonZoomDown")
        self.horizontalLayout_5.addWidget(self.buttonZoomDown)
        self.buttonZoomDefault = QtWidgets.QPushButton(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonZoomDefault.sizePolicy().hasHeightForWidth())
        self.buttonZoomDefault.setSizePolicy(sizePolicy)
        self.buttonZoomDefault.setMinimumSize(QtCore.QSize(30, 30))
        self.buttonZoomDefault.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("ui/zoom_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonZoomDefault.setIcon(icon9)
        self.buttonZoomDefault.setObjectName("buttonZoomDefault")
        self.horizontalLayout_5.addWidget(self.buttonZoomDefault)
        spacerItem4 = QtWidgets.QSpacerItem(1000, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.labelMap = ZoomView(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMap.sizePolicy().hasHeightForWidth())
        self.labelMap.setSizePolicy(sizePolicy)
        self.labelMap.setMinimumSize(QtCore.QSize(200, 200))
        self.labelMap.setMaximumSize(QtCore.QSize(200, 200))
        self.labelMap.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelMap.setObjectName("labelMap")
        self.verticalLayout_4.addWidget(self.labelMap)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.line_4 = QtWidgets.QFrame(MainWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelHistogram = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHistogram.sizePolicy().hasHeightForWidth())
        self.labelHistogram.setSizePolicy(sizePolicy)
        self.labelHistogram.setMinimumSize(QtCore.QSize(300, 150))
        self.labelHistogram.setMaximumSize(QtCore.QSize(300, 150))
        self.labelHistogram.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelHistogram.setObjectName("labelHistogram")
        self.verticalLayout_5.addWidget(self.labelHistogram)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sliderMaxHistogram = QtWidgets.QSlider(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderMaxHistogram.sizePolicy().hasHeightForWidth())
        self.sliderMaxHistogram.setSizePolicy(sizePolicy)
        self.sliderMaxHistogram.setMinimumSize(QtCore.QSize(300, 0))
        self.sliderMaxHistogram.setMaximumSize(QtCore.QSize(300, 16777215))
        self.sliderMaxHistogram.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sliderMaxHistogram.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMaxHistogram.setObjectName("sliderMaxHistogram")
        self.horizontalLayout_7.addWidget(self.sliderMaxHistogram)
        self.label_3 = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(40, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.spinMaxHistogram = QtWidgets.QSpinBox(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMaxHistogram.sizePolicy().hasHeightForWidth())
        self.spinMaxHistogram.setSizePolicy(sizePolicy)
        self.spinMaxHistogram.setMinimumSize(QtCore.QSize(70, 20))
        self.spinMaxHistogram.setMaximumSize(QtCore.QSize(100, 30))
        self.spinMaxHistogram.setObjectName("spinMaxHistogram")
        self.horizontalLayout_7.addWidget(self.spinMaxHistogram)
        spacerItem5 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sliderMinHistogram = QtWidgets.QSlider(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderMinHistogram.sizePolicy().hasHeightForWidth())
        self.sliderMinHistogram.setSizePolicy(sizePolicy)
        self.sliderMinHistogram.setMinimumSize(QtCore.QSize(300, 0))
        self.sliderMinHistogram.setMaximumSize(QtCore.QSize(300, 16777215))
        self.sliderMinHistogram.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMinHistogram.setObjectName("sliderMinHistogram")
        self.horizontalLayout_6.addWidget(self.sliderMinHistogram)
        self.label_4 = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(40, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spinMinHistogram = QtWidgets.QSpinBox(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMinHistogram.sizePolicy().hasHeightForWidth())
        self.spinMinHistogram.setSizePolicy(sizePolicy)
        self.spinMinHistogram.setMinimumSize(QtCore.QSize(70, 20))
        self.spinMinHistogram.setMaximumSize(QtCore.QSize(100, 30))
        self.spinMinHistogram.setObjectName("spinMinHistogram")
        self.horizontalLayout_6.addWidget(self.spinMinHistogram)
        spacerItem6 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.line_5 = QtWidgets.QFrame(MainWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.buttonSwitchSoloAll = QtWidgets.QPushButton(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSwitchSoloAll.sizePolicy().hasHeightForWidth())
        self.buttonSwitchSoloAll.setSizePolicy(sizePolicy)
        self.buttonSwitchSoloAll.setMinimumSize(QtCore.QSize(30, 30))
        self.buttonSwitchSoloAll.setText("")
        self.buttonSwitchSoloAll.setObjectName("buttonSwitchSoloAll")
        self.horizontalLayout_8.addWidget(self.buttonSwitchSoloAll)
        self.buttonSwitchMyEveryone = QtWidgets.QPushButton(MainWidget)
        self.buttonSwitchMyEveryone.setMinimumSize(QtCore.QSize(30, 30))
        self.buttonSwitchMyEveryone.setText("")
        self.buttonSwitchMyEveryone.setObjectName("buttonSwitchMyEveryone")
        self.horizontalLayout_8.addWidget(self.buttonSwitchMyEveryone)
        spacerItem7 = QtWidgets.QSpacerItem(1000, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.buttonDeleteLabel = QtWidgets.QPushButton(MainWidget)
        self.buttonDeleteLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDeleteLabel.sizePolicy().hasHeightForWidth())
        self.buttonDeleteLabel.setSizePolicy(sizePolicy)
        self.buttonDeleteLabel.setMinimumSize(QtCore.QSize(30, 30))
        self.buttonDeleteLabel.setStyleSheet("background-color: rgb(255, 107, 142);")
        self.buttonDeleteLabel.setText("")
        self.buttonDeleteLabel.setIcon(icon6)
        self.buttonDeleteLabel.setFlat(False)
        self.buttonDeleteLabel.setObjectName("buttonDeleteLabel")
        self.horizontalLayout_8.addWidget(self.buttonDeleteLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.tableWidgetLabels = QtWidgets.QTableWidget(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetLabels.sizePolicy().hasHeightForWidth())
        self.tableWidgetLabels.setSizePolicy(sizePolicy)
        self.tableWidgetLabels.setMinimumSize(QtCore.QSize(20, 0))
        self.tableWidgetLabels.setMaximumSize(QtCore.QSize(450, 16777215))
        self.tableWidgetLabels.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetLabels.setObjectName("tableWidgetLabels")
        self.tableWidgetLabels.setColumnCount(5)
        self.tableWidgetLabels.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetLabels.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetLabels.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetLabels.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetLabels.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetLabels.setHorizontalHeaderItem(4, item)
        self.verticalLayout_6.addWidget(self.tableWidgetLabels)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labelInfo = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInfo.sizePolicy().hasHeightForWidth())
        self.labelInfo.setSizePolicy(sizePolicy)
        self.labelInfo.setObjectName("labelInfo")
        self.horizontalLayout_13.addWidget(self.labelInfo)
        spacerItem8 = QtWidgets.QSpacerItem(10000, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addLayout(self.verticalLayout_9)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Nodule me"))
        self.buttonOpen.setText(_translate("MainWidget", "Open"))
        self.buttonSave.setText(_translate("MainWidget", "Save"))
        self.buttonSaveAsNew.setText(_translate("MainWidget", "Save as ..."))
        self.comboBoxUser.setCurrentText(_translate("MainWidget", "user1"))
        self.comboBoxUser.setItemText(0, _translate("MainWidget", "user1"))
        self.comboBoxUser.setItemText(1, _translate("MainWidget", "user2"))
        self.comboBoxUser.setItemText(2, _translate("MainWidget", "user3"))
        self.buttonPen.setToolTip(_translate("MainWidget", "add points of label by click.\n"
" you can end by right ckick."))
        self.buttonPen.setText(_translate("MainWidget", "+"))
        self.buttonTube.setToolTip(_translate("MainWidget", "insert a point of label between points by click."))
        self.buttonPinset.setToolTip(_translate("MainWidget", "move points of label by drag."))
        self.buttonPinset.setText(_translate("MainWidget", "Ed"))
        self.buttonEracer.setToolTip(_translate("MainWidget", "delete points of label by click."))
        self.buttonACMSnake.setToolTip(_translate("MainWidget", "auto generate label by drag. (snake method)"))
        self.labelImage.setText(_translate("MainWidget", "Here is CT image"))
        self.label.setText(_translate("MainWidget", "Your writting label"))
        self.label_2.setText(_translate("MainWidget", "Malignant level"))
        self.radioButton5.setText(_translate("MainWidget", "5"))
        self.radioButton4.setText(_translate("MainWidget", "4"))
        self.radioButton3.setText(_translate("MainWidget", "3"))
        self.radioButton2.setText(_translate("MainWidget", "2"))
        self.radioButton1.setText(_translate("MainWidget", "1"))
        self.label_5.setText(_translate("MainWidget", "Comments"))
        self.label_6.setText(_translate("MainWidget", "Nodule id"))
        self.buttonDeleteWritting.setToolTip(_translate("MainWidget", "delete one writting selecting label."))
        item = self.tableWidgetWritting.horizontalHeaderItem(0)
        item.setText(_translate("MainWidget", "Index"))
        self.buttonOkWritting.setText(_translate("MainWidget", "Regist label >>"))
        self.buttonZoomUp.setText(_translate("MainWidget", "+"))
        self.buttonZoomDown.setText(_translate("MainWidget", "-"))
        self.buttonZoomDefault.setToolTip(_translate("MainWidget", "set default zoom (*1.0)"))
        self.labelMap.setText(_translate("MainWidget", "Here is Map"))
        self.labelHistogram.setText(_translate("MainWidget", "Here is Histogram"))
        self.label_3.setText(_translate("MainWidget", "MAX"))
        self.label_4.setText(_translate("MainWidget", "MIN"))
        self.buttonSwitchSoloAll.setToolTip(_translate("MainWidget", "switch [only this z-index view] or [all z-index view]"))
        self.buttonSwitchMyEveryone.setToolTip(_translate("MainWidget", "switch [only your label view] or [everyone label view]"))
        self.buttonDeleteLabel.setToolTip(_translate("MainWidget", "delete one selecting label "))
        item = self.tableWidgetLabels.horizontalHeaderItem(0)
        item.setText(_translate("MainWidget", "ID"))
        item = self.tableWidgetLabels.horizontalHeaderItem(1)
        item.setText(_translate("MainWidget", "Index"))
        item = self.tableWidgetLabels.horizontalHeaderItem(2)
        item.setText(_translate("MainWidget", "M level"))
        item = self.tableWidgetLabels.horizontalHeaderItem(3)
        item.setText(_translate("MainWidget", "User"))
        item = self.tableWidgetLabels.horizontalHeaderItem(4)
        item.setText(_translate("MainWidget", "Comments"))
        self.labelInfo.setText(_translate("MainWidget", "TextLabel"))

from view.canvas_view import CanvasView
from view.zoom_view import ZoomView
